website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(256))

class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300))
    year = db.Column(db.Integer)
    genre = db.Column(db.String(60))
    poster = db.Column(db.String(100))
    synopsis = db.Column(db.String(10000))
    rating = db.Column(db.Integer)
    watched = db.Column(db.Boolean())

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '@81B6X3&CVuWlu$t'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Movie

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth',__name__)

@auth.route('/login', methods=['Get', 'POST'])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category="error")
        else:
            flash('User does not exist.', category='error')

    return render_template("login.html",user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['Get', 'POST'])
def sign_up():
    if request.method == "POST":
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(username=username).first()

        if user:
            flash('Username is already in use', category='error')
        elif len(username) < 4:
            flash('Username must be greater than 3 characters.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home',user=current_user))

    return render_template("signup.html",user=current_user)

website/views.py
from flask import Blueprint, redirect, render_template, request, flash, jsonify, url_for
from flask_login import login_required, current_user
from .models import Movie
from .tmdbRequester import newMovie, searchForMovie, detailsForMovie
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)

@views.route('/movies')
def movies():
    movies=Movie.query.all()
    return render_template("movies.html",user=current_user, movies=movies)

@views.route('/reset')
@login_required
def reset():
    db.drop_all()
    db.create_all()

@views.route("/admin/new-movie", methods=["GET", "POST"])
@login_required
def new_movie():
    if request.method == "POST":
        query=request.form.get("title")
        response = searchForMovie(query)
        return render_template("confirmation.html", response=response, user=current_user)
    return render_template("tmdb-request.html", user=current_user)

@views.route("/admin/new-movie/", methods=["GET","POST"])
@login_required
def movie_confirmed():
    movie=detailsForMovie(request.args.get("id"))
    if "success" in movie:
        flash("something went wrong",category="error")
    else:
        my_movie=newMovie(movie)
        db.session.add(my_movie)
        db.session.commit()
        flash(f'{movie["original_title"]} added successfully',category="success")
    return redirect(url_for("views.new_movie"))

@views.route("/test-movie", methods=["GET", "POST"])
@login_required
def test_movie():
    if request.method == "POST":
        title = request.form.get("title")
        year = request.form.get("year")
        genre = request.form.get("genre")
        poster = request.form.get("poster")
        synopsis = request.form.get("synopsis")
        new_movie = Movie(title=title, year=year, genre=genre,poster=poster,synopsis=synopsis)
        print(new_movie)
        db.session.add(new_movie)
        db.session.commit()
        print("title: "+title)
        print("year: "+year)
        print("genre: "+genre)
        print("poster: "+poster)
        print("synopsis: "+synopsis)
    return render_template("manual-movie-entry.html", user=current_user)

@views.route('/delete-movie', methods=['POST'])
def delete_movie():
    movie = json.loads(request.data)
    movieId = movie['movieId']
    movie = Movie.query.get(movieId)
    if movie:
        db.session.delete(movie)
        db.session.commit()

    return jsonify({})

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>J&R Cinema</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!--Bootstrap css-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                {% if user.is_authenticated%}
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                <a class="nav-item nav-link" id="add-movie" href="/admin/new-movie">Add Movie</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signup" href="/signup">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        {% if category == 'error' %}
          <div class="alert alert-danger alert-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% else %}
          <div class="alert alert-success alert-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
    {% endif %} {% endfor %} {% endif%} {% endwith %}

    {%block container%}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {%endblock%}


    <!--Bootstrap scripts-->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!--Custom scripts-->
    <script
      type"text/javascript"
      src="{{ url_for('static', filename='index.js')}}"
    ></script>
  </body>
</html>

website/templates/confirmation.html
{% extends "tmdb-request.html" %}

{% block confirm %}
<br />
<ul class="list-group list-group-horizontal d-flex flex-wrap">
{% for i in response["results"][0:10] %}
    <li class="list-group-item">
      <div class="w-154">
        <figure class="figure">
          <a href="/admin/new-movie/?id={{i["id"]}}">
            <img class="rounded" src="https://image.tmdb.org/t/p/original/{{i["poster_path"]}}" width="154"/>
          </a>
          <figcaption class="figure-caption text-center text-wrap">{{ i["title"] }} ({{ i["release_date"]}})</figcaption>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block content %}
<br/>
<div class="text-center" id="logo">
    <img class="rounded" src="./static/Logo5.png"/ width="150px" height="auto">
</div>
<div class="d-flex position-relative" id="database">
    <h3>The Database</h3>
    <a href="{{url_for('views.movies')}}" class="stretched-link"></a>
</div>
<div class="" id="description">
    <p1>The description of what's happening on this website</p1>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{%block content%}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="username">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        name="username"
        placeholder="Enter username"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type"submit" class="btn btn-primary">Login</button>
  </form>
{%endblock%}

website/templates/manual-movie-entry.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <h3 align="center">New Movie</h3>
    <div class="form-group">
        <label for="title">Title</label>
        <input
            type="text"
            class="form-control"
            id="title"
            name="title"
            placeholder="Movie Title..."
        />
    </div>
    <div class="form-group">
        <label for="year">Year</label>
        <input
            type="number"
            class="form-control"
            id="year"
            name="year"
            placeholder="2010..."
        />
    </div>
    <div class="form-group">
        <label for="genre">Genres</label>
        <fieldset>
            <legend>Genres:</legend>
            <div>
                <input type="checkbox" id="action" name="genre" value="action" />
                <label for="action">Action</label>
            </div>
            <div>
                <input type="checkbox" id="adventure" name="genre" value="adventure" />
                <label for="adventure">Adventure</label>
            </div>
            <div>
                <input type="checkbox" id="comedy" name="genre" value="comedy" />
                <label for="comedy">Comedy</label>
            </div>
            <div>
                <input type="checkbox" id="crime" name="genre" value="crime" />
                <label for="crime">Crime</label>
            </div>
            <div>
                <input type="checkbox" id="action" name="drama" value="drama" />
                <label for="drama">Drama</label>
            </div>
            <div>
                <input type="checkbox" id="fantasy" name="genre" value="fantasy" />
                <label for="fantasy">Fantasy</label>
            </div>
            <div>
                <input type="checkbox" id="historical" name="genre" value="historical" />
                <label for="historical">Historical</label>
            </div>
            <div>
                <input type="checkbox" id="horror" name="genre" value="horror" />
                <label for="horror">Horror</label>
            </div>
            <div>
                <input type="checkbox" id="musical" name="genre" value="musical" />
                <label for="musical">Musical</label>
            </div>
            <div>
                <input type="checkbox" id="noir" name="genre" value="noir" />
                <label for="noir">Noir</label>
            </div>
            <div>
                <input type="checkbox" id="romance" name="genre" value="romance" />
                <label for="romance">Romance</label>
            </div>
            <div>
                <input type="checkbox" id="science-fiction" name="genre" value="science-fiction" />
                <label for="science-fiction">Science fiction</label>
            </div>
            <div>
                <input type="checkbox" id="thriller" name="genre" value="thriller" />
                <label for="thriller">Thriller</label>
            </div>
            <div>
                <input type="checkbox" id="western" name="genre" value="western" />
                <label for="western">Western</label>
            </div>
    </fieldset>
    </div>
    <div class="form-group">
        <label for="poster">Poster</label>
        <input
            type="file"
            class="form-control"
            id="poster"
            name="poster"
            accept="image/png, image/jpeg"
        />
    </div>
    <div class="form-group">
        <label for="synopsis">Synopsis</label>
        <textarea
            class="form-control"
            id="synopsis"
            name="synopsis"
        ></textarea>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
{% endblock %}

website/templates/movie-entry.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <h3 align="center">New Movie</h3>
    <div class="form-group">
        <label for="title">Title</label>
        <input
            type="text"
            class="form-control"
            id="title"
            name="title"
            placeholder="Movie Title..."
        />
    </div>
    <div class="form-group">
        <label for="year">Year</label>
        <input
            type="number"
            class="form-control"
            id="year"
            name="year"
            placeholder="2010..."
        />
    </div>
    <div class="form-group">
        <label for="genre">Genres</label>
        <fieldset>
            <legend>Genres:</legend>
            <div>
                <input type="checkbox" id="action" name="genre" value="action" />
                <label for="action">Action</label>
            </div>
            <div>
                <input type="checkbox" id="adventure" name="genre" value="adventure" />
                <label for="adventure">Adventure</label>
            </div>
            <div>
                <input type="checkbox" id="comedy" name="genre" value="comedy" />
                <label for="comedy">Comedy</label>
            </div>
            <div>
                <input type="checkbox" id="crime" name="genre" value="crime" />
                <label for="crime">Crime</label>
            </div>
            <div>
                <input type="checkbox" id="action" name="drama" value="drama" />
                <label for="drama">Drama</label>
            </div>
            <div>
                <input type="checkbox" id="fantasy" name="genre" value="fantasy" />
                <label for="fantasy">Fantasy</label>
            </div>
            <div>
                <input type="checkbox" id="historical" name="genre" value="historical" />
                <label for="historical">Historical</label>
            </div>
            <div>
                <input type="checkbox" id="horror" name="genre" value="horror" />
                <label for="horror">Horror</label>
            </div>
            <div>
                <input type="checkbox" id="musical" name="genre" value="musical" />
                <label for="musical">Musical</label>
            </div>
            <div>
                <input type="checkbox" id="noir" name="genre" value="noir" />
                <label for="noir">Noir</label>
            </div>
            <div>
                <input type="checkbox" id="romance" name="genre" value="romance" />
                <label for="romance">Romance</label>
            </div>
            <div>
                <input type="checkbox" id="science-fiction" name="genre" value="science-fiction" />
                <label for="science-fiction">Science fiction</label>
            </div>
            <div>
                <input type="checkbox" id="thriller" name="genre" value="thriller" />
                <label for="thriller">Thriller</label>
            </div>
            <div>
                <input type="checkbox" id="western" name="genre" value="western" />
                <label for="western">Western</label>
            </div>
    </fieldset>
    </div>
    <div class="form-group">
        <label for="poster">Poster</label>
        <input
            type="file"
            class="form-control"
            id="poster"
            name="poster"
            accept="image/png, image/jpeg"
        />
    </div>
    <div class="form-group">
        <label for="synopsis">Synopsis</label>
        <textarea
            class="form-control"
            id="synopsis"
            name="synopsis"
        ></textarea>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
{% endblock %}

website/templates/movies.html
{% extends "base.html" %}
{%block container%}
<div class="container-fluid">
{%block content%}
<div class="">
<ul class="list-group list-group-horizontal d-flex justify-content-center flex-wrap" id="movies">
    {% for movie in movies %}
        <li class="list-group-item" id="movie-poster">
            <figure class="figure">
                <img class="rounded" src="{{ movie.poster }}" width="350" >
                <!-- <figcaption class="figure-caption text-center">{{ movie.title }}{% block admin %}{%endblock%}</figcaption> -->
            </figure>
        </li>
    {% endfor %}
</ul>
</div>
{%endblock%}
</div>
{%endblock%}

website/templates/signup.html
{% extends "base.html" %}
{%block content%}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter username"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type"submit" class="btn btn-primary">Submit</button>
</form>
{%endblock%}

website/templates/tmdb-request.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <h3 align="center">New Movie</h3>
    <div class="form-group">
      <label for="title">Movie Title</label>
      <input
        type="text"
        class="form-control"
        id="title"
        name="title"
        placeholder="Movie Title"
      />
    </div>
    <br />
    <button type"submit" class="btn btn-primary">Submit</button>
</form>
{% block confirm%}
{% endblock %}
{% endblock %}